name: push

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_USERNAME }}

      - name: Gather metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: registry.digitalocean.com/vatsim-containers/go-ptd-bot
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,priority=300,prefix=

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
